language: node_js
node_js: lts/*

before install: hexo clean

script: 
  - hexo generate
  - cd ./public
  - git init
  - git config user.name "travis script"
  - git add .
  - git commit -m 'Update blog'
  - echo $github_token@$github_repo
  - git push https://$github_token@$github_repo

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: 1f76a2b22f707eea44517202f160deb60afc31d4
#   keep-history: true
#   on:
#     branch: master

env:
  global:
    github_token: 1f76a2b22f707eea44517202f160deb60afc31d4
    github_repo: github.com:hq229075284/blog.git
  