language: node_js
node_js: lts/*

cache:
  directories:
    - "node_modules"
    
before install: hexo clean

script: 
  - hexo generate
  - cd ./public
  - git init
  - git config user.name "travis script"
  - git add .
  - git commit -m 'Update blog'
  - echo https://$github_token@$github_repo
  - echo https://0f3763b47e0cc44ceafd458ee3f975692fe93eb4@github.com/hq229075284/blog.git
  - git push https://$github_token@$github_repo master

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: 0f3763b47e0cc44ceafd458ee3f975692fe93eb4
#   keep-history: true
#   on:
#     branch: master
env:
  global:
    github_repo: github.com:hq229075284/blog.git
  